[project]
name = "mcp-client-server"
version = "0.1.0"
description = "A Simple Weather forcaste MCP SERVER "
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-groq>=0.3.7",
    "mcp-use>=1.3.10",
    "mcp[cli]>=1.13.1",
    "nest-asyncio>=1.6.0",
]
